name: Merge Feature/BugFix to dev and main

on:
  push:
    brnaches:
      - 'features/*'
      - 'bugfix/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout node
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  merge-to-dev:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to dev
        run : |
          git config --local user.email "harmish2111patel@gmail.com"
          git config --local user.name "harmishpatel21"
          git remote update
          git fetch
          git checkout dev
          git pull origin dev
          git merge --no-ff ${{ github.ref }}
          git push origin dev
  
  merge-to-main:
    runs-on: ubuntu-latest
    needs: merge-to-dev
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff dev
          git push origin main

  cleanup:
    runs-on: ubuntu-latest
    needs: merge-to-main
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete feature/bugfix branch
        run: |
          git branch -d ${{ github.ref }}
          git push origin --delete ${{ github.head_ref }}




